### ISSUE TITLE
Is the latest version the official version? Can it be used?

### ISSUE THREAD

**Issue by zorro0799** [code-with-max/godot-google-play-iapp#3]
Is the latest version the official version? Can it be used?

**Comment by code-with-max** [comment]
It for Godot version 4.2+ with Google billing version 7.
Check this: https://developer.android.com/google/play/billing/deprecation-faq
We will have to use the new version, because Google stops accepting updates of the old ones in August.

I have two methods left to do: consume and acknowledge, as well as fix a couple of signals, after which you can use the plugin without any restrictions.

**Comment by code-with-max** [comment]
Done.
You can use it!

**Comment by zorro0799** [comment]
Think You!!!!
