### ISSUE TITLE
[Question] Why do we have to do our game code in 'process_purchase' method?

### ISSUE THREAD

**Issue by Mefistosss** [code-with-max/godot-google-play-iapp#6]
Hello @code-with-max
Thank you for your plugin!

You suggest to do our game code in [this](https://github.com/code-with-max/godot-google-play-iapp/blob/be71531d191ad2a4989ba8658e40bee2f3367790/examples/billing_example.gd#L191) and in [this](https://github.com/code-with-max/godot-google-play-iapp/blob/be71531d191ad2a4989ba8658e40bee2f3367790/examples/billing_example.gd#L200) places.
Why do we need to do it there?

Maybe ([purchase_consumed](https://github.com/code-with-max/godot-google-play-iapp/blob/be71531d191ad2a4989ba8658e40bee2f3367790/examples/billing_example.gd#L230) and [purchase_acknowledged](https://github.com/code-with-max/godot-google-play-iapp/blob/be71531d191ad2a4989ba8658e40bee2f3367790/examples/billing_example.gd#L235)) events are the best places?

Please explain if I'm wrong.
Thank you!

**Comment by code-with-max** [comment]
Hi @Mefistosss you're right about that, too.
That is why I did not make additional scripts that the developer should link to the nodes, but left the freedom of choice.

> Maybe ([purchase_consumed](https://github.com/code-with-max/godot-google-play-iapp/blob/be71531d191ad2a4989ba8658e40bee2f3367790/examples/billing_example.gd#L230) and [purchase_acknowledged](https://github.com/code-with-max/godot-google-play-iapp/blob/be71531d191ad2a4989ba8658e40bee2f3367790/examples/billing_example.gd#L235)) events are the best places?

Yes, this is the right place, because the purchase processing will continue only after confirmation. But you should understand that you will need additional logic to store a unique purchase token.
